#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

banner "Access Trace: GitHub Integration & Bug Recording Setup"

# ── Stage 1: Register GitHub App ──────────────────────────────────────────
stage "Register GitHub App"
existing_client_id=$(_existing "VITE_GITHUB_APP_CLIENT_ID" || true)
reuse_existing=false

if [[ -n "$existing_client_id" ]]; then
  say "Found existing GitHub App Client ID: $existing_client_id"
  if confirm "Keep existing GitHub App ($existing_client_id)?"; then
    VITE_GITHUB_APP_CLIENT_ID="$existing_client_id"
    reuse_existing=true
    say "Using existing GitHub App."
  fi
fi

if [[ "$reuse_existing" != "true" ]]; then
  say "Register a lightweight GitHub App. No client secret or private key is needed."
  open_url "https://github.com/settings/apps/new"
  step "Set 'GitHub App name' (e.g. Access Trace - your-name)."
  step "Set 'Homepage URL' (e.g. https://github.com/dequelabs/axe-core or your repo URL)."
  step "Check 'Enable Device Flow'."
  step "Under 'Repository permissions', set 'Issues' to 'Read and write'."
  step "Check 'Expire user-to-server tokens'."
  step "Under 'Where can this GitHub App be installed?', choose 'Only on this account'."
  step "Click 'Create GitHub App' at the bottom of the page."
  pause "After creating the app, press Enter to enter your App details"

  step "On your app's General settings page, copy the 'Client ID' (starts with 'Iv1.' or 'Iv23.')."
  ask VITE_GITHUB_APP_CLIENT_ID "Enter your GitHub App Client ID:"
  write_env VITE_GITHUB_APP_CLIENT_ID "$VITE_GITHUB_APP_CLIENT_ID"
fi

step "Optional: copy the 'Public link' URL (e.g. https://github.com/apps/your-app-name)."
ask VITE_GITHUB_APP_INSTALLATION_URL "Enter Public link / Installation URL (or Enter to skip):"
if [[ -n "$VITE_GITHUB_APP_INSTALLATION_URL" ]]; then
  write_env VITE_GITHUB_APP_INSTALLATION_URL "$VITE_GITHUB_APP_INSTALLATION_URL"
fi

# ── Stage 2: Install GitHub App on Your Account ───────────────────────────
stage "Install GitHub App on Your Account"
say "GitHub Apps require installation on your account/org to access repositories."
open_url "https://github.com/settings/apps"
step "Click on your newly created GitHub App in the list."
step "In the left sidebar, click 'Install App'."
step "Click the green 'Install' button next to your account or organization."
step "Choose 'All repositories' or select the specific repository where bugs should be logged."
step "Click 'Install' (or 'Save')."
pause "Once installed with repository permissions granted, press Enter"

# ── Stage 3: Build Extension with Configured Client ID ────────────────────
stage "Build Extension"
say "Vite compiles your GitHub App Client ID into the unpacked extension bundle."
step "Running 'pnpm build'..."
pnpm build
note "Extension bundle compiled to .output/chrome-mv3"
pause "Build finished. Press Enter to proceed to Chrome extension setup"

# ── Stage 4: Load or Reload Extension in Chrome ───────────────────────────
stage "Load Unpacked Extension in Chrome"
say "Load or reload the compiled extension into Chrome Developer Mode:"
open_url "chrome://extensions"
step "Ensure 'Developer mode' switch is ON in the top right corner."
step "If Access Trace is already loaded, click the reload (circular arrow) icon."
step "If not yet loaded, click 'Load unpacked' and select:"
note "  $(pwd)/.output/chrome-mv3"
pause "Once the extension is loaded/reloaded in Chrome, press Enter"

# ── Stage 5: Authenticate via Device Flow ────────────────────────────────
stage "Connect GitHub via Device Flow"
say "Authenticate the extension with GitHub using OAuth Device Flow:"
step "Open the Access Trace Integrations page:"
note "  chrome-extension://<extension-id>/options.html#/integrations"
step "Click 'Connect GitHub'."
step "Copy the 8-character user code shown in the modal (e.g. ABCD-1234)."
open_url "https://github.com/login/device"
step "Paste the code in GitHub's device activation page and click 'Continue'."
step "Click 'Authorize' to grant the requested issue permissions."
pause "Once the Options page updates to 'Connected as @username', press Enter"

# ── Stage 6: Configure Domain-to-Repository Mapping ───────────────────────
stage "Map Tested Domain to Repository"
say "Access Trace maps inspected website domains directly to your GitHub repository:"
step "On the Integrations page (options.html#/integrations), locate 'Add Domain Mapping'."
step "In 'Target repository', select your installed repository from the dropdown."
note "  (If empty, click 'Refresh Repositories' to re-fetch installations)"
step "In 'Issue label', select an existing label (e.g. 'bug') or leave default."
step "In 'Domain key', enter the domain you want to test (e.g. 'localhost:3000' or '*')."
step "Click 'Save mapping'."
pause "Once the mapping appears in 'Mapped Repositories', press Enter"

# ── Stage 7: Verify Bug Recording from Side Panel ─────────────────────────
stage "Test Bug Recording from Side Panel"
say "Test filing your first accessibility bug directly to GitHub:"
step "Open a web page matching your domain mapping in Chrome (e.g. http://localhost:3000)."
step "Open the Access Trace side panel from the extension icon."
step "Click 'Scan this page'."
step "Expand any finding card, scroll to the footer, and click 'Add issue on GitHub'."
step "Confirm the button turns into 'View GitHub issue' with a clickable link."
pause "Press Enter to see the configuration summary"

finish
